application_port: 8000
application:
    port: 8000
    host: localhost
database:
    host: "localhost"
    port: 5432
    username: "postgres"
    password: "postgres"
    database_name: "newsletter"
email_client:
    base_url: "localhost"
    sender_email: "test@gmail.com"
    authorization_token: "my-secret-token"
    timeout_ms: 10000