application_port: 8000
application:
    port: 8000
    host: localhost
database:
    host: "localhost"
    port: 5432
    username: "postgres"
    password: "postgres"
    database_name: "newsletter"
